version: '3'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=hmucs@yahoo.co.uk
      - URL=hmucs.co.uk
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=e916251d-df3d-4382-a07b-2ad137142020
      - TZ=GMT
    volumes:
      - ./nginx-config:/config
  resume:
    image: harryu/resume
    ports:
      - 5000:5000
    restart: always
  radarr:
    image: linuxserver/radarr
    ports:
      - 7878:7878
    volumes:
      - /radarr_data:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    volumes:
      - /sonarr_data:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
  jackett:
    image: linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - /jackett_data:/config
      - /mnt/downloads:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=GMT
  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "980:80/tcp"
      - "9443:443/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.0.21
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: 192.168.0.21:980
    volumes:
      - '/etc/pihole/:/etc/pihole/'
      - '/var/log/pihole.log:/var/log/pihole.log'
    restart: always
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 2368:2368
    environment:
      NODE_ENV: production
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      mail__transport: SMTP
      mail__service: 'Gmail'
      mail__options__host: 'smtp.gmail.com'
      mail__options__port: 465
      mail__options__secureConnection: 'true'
      mail__options__auth__user: 'hmucs1@gmail.com'
      mail__options__auth__pass: 'B%Z9iE$$1!x'
      url: https://blog.hmucs.co.uk
  ghost_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  influxdb:
    image: influxdb:latest
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=password
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: grafana/grafana
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    #environment:
    #  GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
    #  GF_SERVER_DOMAIN: hmucs.co.uk
    ports:
      - 3000:3000
    restart:
      always
