version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./reverseproxy:/etc/nginx/sites-enabled/reverseproxy
      - ./ssl-153.duckdns.org.conf:/etc/nginx/snippets/ssl-153.duckdns.org.conf
      - ./ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - /etc/letsencrypt/live/153.duckdns.org/fullchain.pem:/etc/letsencrypt/live/153.duckdns.org/fullchain.pem
      - /etc/letsencrypt/live/153.duckdns.org/privkey.pem:/etc/letsencrypt/live/153.duckdns.org/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
  resume:
    image: harryu/resume
    ports:
      - 5000:5000
    restart: always
  guac-db:
    hostname: guac-db
    build:
      context: .
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  guacd:
    hostname: guacd
    image: guacamole/guacd:0.9.12-incubating
    restart: always

  guacamole:
    image: guacamole/guacamole:0.9.12-incubating
    restart: always
    ports:
      - 8080:8080
    links:
      - guacd
      - guac-db
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guac-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  data:
