version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./reverseproxy:/etc/nginx/sites-enabled/reverseproxy
      - ./ssl-153.duckdns.org.conf:/etc/nginx/snippets/ssl-153.duckdns.org.conf
      - ./ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - /etc/letsencrypt/live/153.duckdns.org-0002/fullchain.pem:/etc/letsencrypt/live/153.duckdns.org-0002/fullchain.pem
      - /etc/letsencrypt/live/153.duckdns.org-0002/privkey.pem:/etc/letsencrypt/live/153.duckdns.org-0002/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
  resume:
    image: harryu/resume
    ports:
      - 5000:5000
    restart: always
  radarr:
    image: linuxserver/radarr
    ports:
      - 7878:7878
    volumes:
      - /radarr_data:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
