version: '3'
services:
  reverse_proxy:
    image: linuxserver/letsencrypt
    container_name: reverse_proxy
    dns:
      - 8.8.8.8
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=hmucs@yahoo.co.uk
      - URL=hmucs.co.uk
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - TZ=GMT
    cap_add:
      - NET_ADMIN
    volumes:
      - ./nginx-config:/config
  resume:
    image: harryu/resume
    container_name: website
    dns:
      - 8.8.8.8
    ports:
      - 5000:5000
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    dns:
      - 8.8.8.8
    ports:
      - 7878:7878
    volumes:
      - /radarr_data:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    dns:
      - 8.8.8.8
    ports:
      - 8989:8989
    volumes:
      - /sonarr_data:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    dns:
      - 8.8.8.8
    ports:
      - 9117:9117
    volumes:
      - /jackett_data:/config
      - /mnt/downloads:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=GMT
    restart: unless-stopped
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "980:80/tcp"
      - "9443:443/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.1.35
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: 192.168.1.35:980
    volumes:
      - '/etc/pihole/:/etc/pihole/'
      - '/var/log/pihole.log:/var/log/pihole.log'
    restart: unless-stopped
  ghost:
    image: ghost:latest
    container_name: blog
    dns:
      - 8.8.8.8
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      NODE_ENV: production
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      mail__transport: SMTP
      mail__service: 'Mailgun'
      mail__options__auth__user: postmaster@hmucs.co.uk
      mail__options__auth__pass: 70b1be20bcdf45bf05da76c02fef071b-c8c889c9-ecdaee53
      url: https://blog.hmucs.co.uk
  ghost_db:
    image: mysql:5.7
    container_name: blog_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=password
    ports:
      - 8083:8083
      - 8086:8086
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    dns:
      - 8.8.8.8
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
      - ./nginx-config/keys/letsencrypt/fullchain.pem:/cert.pem
      - ./nginx-config/keys/letsencrypt/privkey.pem:/key.pem
    user: "1000"
    environment:
      - PGID=1000
      - PUID=1000
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SERVER_DOMAIN=hmucs.co.uk
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/cert.pem
      - GF_SERVER_CERT_KEY=/key.pem
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
    ports:
      - 3001:3000
    restart: unless-stopped
  telegraf:
    image: nuntz/telegraf-snmp
    container_name: telegraf
    dns:
      - 8.8.8.8
    restart: unless-stopped
    links:
      - influxdb
    volumes:
      - /opt/appdata/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /opt/appdata/telegraf/mibsdir:/root/.snmp/mibs:ro
  chronograf:
    image: chronograf:0.12
    container_name: chronograf
    dns:
      - 8.8.8.8
    restart: unless-stopped
    volumes:
      - /opt/appdata/chronograf:/var/lib/chronograf
    ports:
      - "10000:10000"
    links:
      - influxdb
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi
    dns:
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/appdata/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    dns:
      - 8.8.8.8
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer:/data
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    dns:
      - 8.8.8.8
    restart: unless-stopped
    environment:
      - VERSION=plexpass
      - PUID=1000
      - PGID=1000
      - TZ=GMT
      - PLEX_CLAIM="kYx6LskNGnEnzcHzHWZz"
    volumes:
      - transcode:/transcode
      - config:/config
      - /mnt/movies:/data/movies
      - /mnt/downloads:/data/downloads
      - /mnt/tv:/data/tvshows
    network_mode: host
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    dns:
      - 8.8.8.8
    network_mode: bridge
    restart: unless-stopped
    links:
      - guacd:guacd
      - guac-postgres:postgres
    environment:
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=password
    ports:
      - 8383:8080
  guacd:
    image: guacamole/guacd
    container_name: guacd
    network_mode: bridge
    restart: unless-stopped
  guac-postgres:
    image: postgres
    container_name: guac-postgres
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /tmp/scripts:/tmp/scripts
      - /opt/appdata/postgres:/var/lib/postgresql/data
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - 1080:80
      - 10443:443
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=GMT
    volumes:
      - /opt/appdata/heimdall:/config
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    dns:
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
        #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /opt/appdata/transmission:/config
      - /mnt/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  cowyo:
    image: schollz/cowyo
    container_name: cowyo
    volumes:
      - /opt/appdata/cowyo:/data
    ports:
      - 8050:8050
    restart: unless-stopped
  rwtxt:
    image: schollz/rwtxt
    container_name: rwtxt
    volumes:
      - /opt/appdata/rwtxt:/data
    ports:
      - 8152:8152
    restart: unless-stopped
  lychee:
      image: linuxserver/lychee
      container_name: lychee
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - /opt/appdata/lychee/config:/config
        - /mnt/photos/Toby:/pictures
      ports:
        - 1180:80
      restart: unless-stopped
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/piwigo/config:/config
    ports:
      - 1280:80
    restart: unless-stopped
    links:
      - piwigo_db:mysql
  piwigo_db:
    image: mysql:5
    container_name: piwigo_db
    volumes:
      - /opt/appdata/piwigo_db:/var/lib/mysql
    environment:
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=piwigo
      - MYSQL_DATABASE=piwigo
      - MYSQL_ROOT_PASSWORD=password
  openldap:
    container_name: openldap
    image: osixia/openldap:1.3.0
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ORGANISATION=hmucs
      - LDAP_DOMAIN=hmucs.co.uk
      - LDAP_BASE_DN=dc=hmucs,dc=co,dc=uk
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_TLS_CIPHER_SUITE=NORMAL
      - LDAP_TLS_VERIFY_CLIENT=allow
      - HOSTNAME=openldap
      - LDAP_CONFIG_PASSWORD=password
    tty: true
    stdin_open: true
    volumes:
      - /opt/appdata/openldap/ldap:/var/lib/ldap
      - /opt/appdata/openldap/slapd.d:/etc/ldap/slapd.d
      - /opt/appdata/openldap/service/slapd/assets/certs/:/container/service/slapd/assets/certs/
  ldapadmin:
    container_name: ldapadmin
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443
    links:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - /opt/appdata/openvpn-data/conf:/etc/openvpn

volumes:
  config:
    external: true
  transcode:
    external: true
